---
title: "Toolik Chlorophyll Concentrations"
author: "Ryan Munnikhuis"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
```
## Read in toolik_chlorphyll.csv as data frame stored as  `toolik_chlorphyll`
```{r}
toolik_chlorophyll = read_csv(here::here("data", "data-raw", "toolik_chlorophyll.csv"), 
                                         
                                         na = ".")
```
Explore the imported data with `skimr:skim()`, `names()`, `dim()`, `summary()`

```{r}

names(toolik_chlorophyll)

dim(toolik_chlorophyll)

summary(toolik_chlorophyll)
```
```{r}
toolik_chlorophyll = toolik_chlorophyll %>% clean_names
```
## Create a scatterplot of depth vs chlorophyll A concnetration 

- make point size   `size` changed on the concentration 
- make all points "cyan"
- Update the theme to `theme_dark()`
```{r}
toolik_chlorophyll_plot = ggplot(data = toolik_chlorophyll, 
                                  aes(x = active_chl_a_ug_l, y = depth)) + geom_point(aes(size = active_chl_a_ug_l),
                                  color = "cyan",
                                  alpha = 0.5)
                            
                                                                                    
toolik_chlorophyll_plot
```
```{r}
ggsave(here::here("figs", "clorohpyll_graph.jpg"), plot = toolik_chlorophyll_plot)
```

